.TH ANALYTICS 1 LOCAL
.SH NAME
analytics - start the rebase analytics engine
.SH SYNOPSIS
.B analytics [options]
.B [-i] [-d
.I directory
.B ] [-h] [-i] [-v]
.I file
.B ...
.SH AVAILABILITY
Everywhere
.SH DESCRIPTION
analytics starts the rebase analytics engine
.SH OPTIONS
.IP "-h --help"
Show help text
.IP "-d --data-dir directory"
Use an alternative data directory
.IP "-i --interactive"
Start up in interactive mode
.IP -v
Enable verbose messaging
.SH AUTHOR
Edward Kmett
